### ISSUE TITLE
Does this code come with an open-source license?

### ISSUE THREAD

**Issue by dhague** [vadimsva/popModal#1]
Is this licensed under Apache or MIT open-source licenses?

Many thanks,
Darren

**Comment by vadimsva** [comment]
Yes, it's open-source.

**Comment by dhague** [comment]
Thank you, but which open-source licence? Please see https://help.github.com/articles/open-source-licensing

Thanks again,
Darren

**Comment by vadimsva** [comment]
Add license file. MIT license.

**Comment by dhague** [comment]
Awesome - thanks!
