### ISSUE TITLE
IE9 issue

### ISSUE THREAD

**Issue by Sherbert99** [vadimsva/popModal#12]
I found an issue with the "dialogModal" examples in IE9 which I can't figure out a fix for.

In IE9 if you open the examples page "index.html".  Then in the tab menu go to "dialogModal". Then click either one of the examples and you will see the black overlay show but not popup box.

Any idea on what is causing this?

Tested it with: 1.18 [05.08.15] and 1.19 [04.09.15]

Thanks

**Comment by vadimsva** [comment]
IE9 doen't support many css properties such as animation that is used in my plugin.
You need update IE to 10+ version.
