### ISSUE TITLE
Popmodal on dynamic elements

### ISSUE THREAD

**Issue by atwellpub** [vadimsva/popModal#15]
I'm having an issue where popModal is not creating a popup if the element was not registered in the dom initially. 

For example if I add a row that has a popModal powered button the button will not work. If I save the data and reload the page with my new row showing up then the popModal popup works. 

Any idea how to solve it?

**Comment by vadimsva** [comment]
Hi, after you have add a row, need to call the script that runs popModal

**Comment by atwellpub** [comment]
Hey thank you for the attention, I believe we are, take a look at our code:

```
<script type='text/javascript'>
        jQuery( document ).ready( function() {

            /* Add listener to throw popup on button click */
            jQuery('body').on( 'click' , '.lead-fields-button' , function( ) {
                jQuery('#' + this.id ).popModal({
                    html: jQuery('#lead_fields_popup_container').html(),
                    placement : 'bottomLeft',
                    showCloseBut : true,
                    onDocumentClickClose : true,
                    onDocumentClickClosePrevent : '',
                    overflowContent : false,
                    inline : true,
                    beforeLoadingContent : 'Please, waiting...',
                    onOkBut : function(){ },
                    onCancelBut : function(){ },
                    onLoad : function(){ },
                    onClose : function(){ }
                });
            });

        });
```

**Comment by vadimsva** [comment]
Ok, for example simple code.
Create button
$('body').append('<button id="btn">New button</button>');

After init popModal
$('#btn').click(function(){
  $(this).popModal({
    html: 'hello'
  });
});

When you save this button and reload page, you also need to save this script.
