### ISSUE TITLE
Not working with jQuery1.11.3

### ISSUE THREAD

**Issue by rkintali** [vadimsva/popModal#19]
Hi, 

I imported this into my workspace. The pop modal is working when the jQuery version is 1.12 or above, but not working with 1.11.3 (which is the version that our organization is using).

Are there any plans to make it work with jQuery 1.11 or lesser version?

Kind regards,

**Comment by vadimsva** [comment]
Hi, I'm testing on 1.11 and all works fine. Can you use not min version and tell where the error?
Use ver 1.23 [11.04.16]
