### ISSUE TITLE
dialogModal moves up after being displayed.

### ISSUE THREAD

**Issue by roblo** [vadimsva/popModal#2]
I've noticed that when I call dialogModal(), the dialog is displayed and then slightly moves up a bit.  Even on the [example page | http://vadimsva.github.io/popModal] it's happening there as well.  Is there anything I should do to prevent the dialog from moving?

Thanks for the component.  
Rob.

**Comment by vadimsva** [comment]
This is feature, is not a bug.
May be need to add parameter - effect. And when effect: 'none', there is no moves.

**Comment by roblo** [comment]
My mistake.  Thanks for the quick response.  
Cheers.
