### ISSUE TITLE
Hot to use Dalog POPUPMODAL in different DIV tags

### ISSUE THREAD

**Issue by ajaym193** [vadimsva/popModal#20]
I am currently trying to use DIALOG popup modal in multiple places in same HTML file to display different information but it is not working. I have done this by simply copy-paste the DIV portion wherever i have needed it.

Can you gugide me as to how make it work in multiple places.
I will be obliged
Regards
Ajay

**Comment by vadimsva** [comment]
Hi, 
You can create multiple dialogs and call it when you need it or you can use one, then you need to change the content at the show, you can see it in the demo.
For example:
$('#content').dialogModal({
  onLoad : function(el, current) {
    el.find('.dialogModal_header span').text('Page 3');
    $.ajax({url : 'ajax.html'}).done(function(content){
      el.find('.dialogModal_content').html(content);
    });
  }
});
