### ISSUE TITLE
Don't hide the div content?

### ISSUE THREAD

**Issue by jlcbaci** [vadimsva/popModal#21]
Hello, 

I have implement the sample popModal and this is run fine. My question is how to hold the div hold show when i clic the button to show the div content. (I don´t want when i clic the button no hidden the div content).

Hope you can help me the issue?..

thank you

**Comment by vadimsva** [comment]
Hi, I did not quite understand you. At one time is only one popmodal window shows, when you open new popmodal window, previous will be closed.

**Comment by jlcbaci** [comment]
Hello, Right, as you say when you open a new window popmodal, previous close. I want the div layer remains and thus can not be closed .

**Comment by vadimsva** [comment]
This is the idea of the work, focus on the active window. Opening the new window - the old one is closing.

**Comment by jlcbaci** [comment]
I understand, but it is possible to not only maintain close and both display. That attempt a small textarea with little info and simultaneously with popmodal complete information is displayed. It would be nice to include options in the function parameter.

**Comment by vadimsva** [comment]
No, this is impossible to do. I need rewrite all code for this.
