### ISSUE TITLE
Feature Request: Add option for custom class

### ISSUE THREAD

**Issue by ben-eSM** [vadimsva/popModal#23]
By adding an option to define an additional custom css class for the popmodal container it would be easier to use multiple custom styled modals.

**Comment by vadimsva** [comment]
You can use onLoad function for this, for example
$($(this)[0].html[0].offsetParent).attr('data-class','myclass');
or
$($(this)[0].html[0].offsetParent).attr('id','myid');
and in css use
.popModal[data-class='myclass'] {}
or #myid {}
