### ISSUE TITLE
Can not get input value 

### ISSUE THREAD

**Issue by LLCF** [vadimsva/popModal#24]
I put an "input" on confirmModal_content. 
like:

\<div id="content" style="display:none"\>
	\<div class="confirmModal_content"\>
		\<input type="text"  id="SC" size="12" class="form-control" \>
	\</div\>
	\<div class="confirmModal_footer"\>
		\<button type="button" class="btn btn-primary" data-confirmmodal-but="ok"\>OK\</button\>
		\<button type="button" class="btn btn-default" data-confirmmodal-but="cancel"\>Cancel\</button\>
	\</div\>
\</div\>

But I can't not get the input value by `document.getElementById("SC").value`

**Comment by vadimsva** [comment]
Use new version 1.25
$('#content').confirmModal({
  topOffset : 0,
  onOkBut : function(event, el) {},
  onCancelBut : function(event, el) {},
  onLoad : function(el) {
    el.find('.confirmModal_content #SC')....
  },
  onClose : function(el) {}
});
