### ISSUE TITLE
DialogModal doesn't show gmap

### ISSUE THREAD

**Issue by miltonbo** [vadimsva/popModal#25]
I've written the code using bootstrap dialog, it worked ok, but when It was changed to DialogModal, it didn't work anymore, I tried a lot of solutions, but I couldn't solve it, the map container of the gmap is showed as a grey background, but nothing more is showed.

**Comment by vadimsva** [comment]
You need use onLoad function to initialize gmap, and don't use id, because dialogModal copy content from source and show popup

**Comment by miltonbo** [comment]
I tried that, but the problem was not solved.
There is another issue there, because I configured the popModal to launch the dialog with this content, but the content is not working correctly, I suppose you took the control of the events inside the form, because my click controller doesn't work anymore when I put the form inside the popModal.
