### ISSUE TITLE
IE error [Object doesn't support property or method 'append'][Unable to get property 'innerHTML' of undefined or null reference]

### ISSUE THREAD

**Issue by burhanfarooqws** [vadimsva/popModal#28]
Hi,

I have little issue in working of the popModal in IE11, in my implementation i have no problem in other browsers but for IE11 I am getting same error which is occurring on the sample page of yours.

![image](https://user-images.githubusercontent.com/17730402/34745712-39d65d64-f5b3-11e7-8813-0b56db6a738f.png)
above on dialogmodal

![image](https://user-images.githubusercontent.com/17730402/34745784-7983e756-f5b3-11e7-974a-4494e19e01c3.png)
above on confirm.

If you could help as I have implemented it heavily on my app.
any work-around will be appreciated.

Thanks

**Comment by vadimsva** [comment]
Hi, I fixed it. Download updated files
