### ISSUE TITLE
inline bind moves contral content without scroll bar

### ISSUE THREAD

**Issue by EddieE1** [vadimsva/popModal#4]
HI I noticed today that when I move my page to a wider screen that does not have a scroll bar displayed,  when you click on the button to display the content everything shifts about 20 pixels to the left. I have even tried with the original file and deleted everything except the default params and inline bind and same issue. I have even tried forcing a scroll bar using: 
html {
       overflow-y: scroll;
}

Yet same issue. Is there a fix for this?

Thanks

Eddie

**Comment by vadimsva** [comment]
Hi, I understand we are talking about dialogModal. Yes it's a bug, I will fix it next release.
Thanks for feedback

**Comment by EddieE1** [comment]
Thank you and thanks for a great script ;-)
