### ISSUE TITLE
beforeLoadingContent and data- attributes.

### ISSUE THREAD

**Issue by shenanhawkins** [vadimsva/popModal#5]
beforeLoadingContent is hard-coded.  Please allow the user to specify it as an option, either globally, or before calling the popup.  "Please, waiting..." is awkward English.  I like to use <progress /> element, personally.

Also, are you able to change all your data- attributes to lower case?  See:  http://stackoverflow.com/questions/20985204/does-jquery-internaly-converts-html5-data-attribute-keys-to-lowercase    This seems to indicate you should use lower-case characters only, maybe put dashes instead of upper...    Thanks!

**Comment by vadimsva** [comment]
Ok, I'll fix it in the next release.
Thanks
